### PR TITLE
fix: normalize slashes on Windows paths

### PR DESCRIPTION
**Pull request by targos**

### CODE REVIEW

**Comment by thetutlage** [comment]
How about using https://github.com/sindresorhus/slash, it handles couple of more cases?

**Comment by targos** [comment]
SGTM. Should I call it unconditionally or only for windows?

**Comment by thetutlage** [comment]
I think, we can all it unconditionally, since it produces the same result, though calling it conditionally will avoid unnecessary computations

**Comment by targos** [comment]
The issue with the `hasNonAscii` check is that we wouldn't support projects with non-ascii characters in the path

**Comment by thetutlage** [comment]
Yeah, have to think. To be honest, I have no idea how well the nanomatch with work with `non-ascii` characters. I think, we should add tests with handful of cases.

For now, I believe, let's stick to a normal regex replace, until test suite is added

**Pull request merged**
